name: script
channels:
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - beautifulsoup4=4.9.1
  - requests=2.24.0
  - python=3.8.5
  - transformers=3.1.0
  - pip:
      - lxml==4.5.2
      - str2bool==1.1
      - quoters==0.7
